In [1]:
import pandas as pd
df = pd.read_csv("game_info.csv")
df.head()

,id,slug,name,metacritic,released,tba,updated,website,rating,rating_top,...,developers,genres,publishers,esrb_rating,added_status_yet,added_status_owned,added_status_beaten,added_status_toplay,added_status_dropped,added_status_playing
0,1,dgeneration-hd,D/Generation HD,NaN,2015-10-23,False,2019-09-17T11:58:57,http://dgeneration.net,0.0,0,...,West Coast Software,Adventure||Puzzle,West Coast Software,Everyone 10+,4,88,2,2,0,0
1,10,g-prime,G Prime Into The Rain,NaN,2016-01-06,False,2019-11-06T23:04:19,NaN,0.0,0,...,Soma Games,Simulation||Indie,Immanitas Entertainment||Code-Monkeys,Everyone,2,42,2,0,0,0
2,100,land-sliders,Land Sliders,NaN,2015-09-24,False,2019-10-22T13:56:16,http://prettygreat.com,0.0,0,...,Prettygreat Pty,Adventure||Arcade,Prettygreat Pty,Everyone 10+,0,2,2,0,1,0
3,1000,pixel-gear,Pixel Gear,NaN,2016-10-20,False,2019-08-28T22:16:02,https://www.facebook.com/Geronimo-Interactive-...,0.0,0,...,Oasis Games||Geronimo Interactive,Action||Indie,Geronimo Interactive,Teen,0,1,0,0,0,0
4,10000,gods-and-idols,Gods and Idols,NaN,2016-12-12,False,2019-09-17T13:37:13,http://www.godsandidols.com/,0.0,1,...,Viking Tao,RPG||Strategy||Massively Multiplayer,Viking Tao,NaN,2,79,0,0,0,0

In [2]:
df.info()          # column types and nulls
df.duplicated().sum()  # duplicate rows
df.isnull().sum()  # missing values per column

id                           0
slug                         2
name                         3
metacritic              469684
released                 24199
tba                          0
updated                      0
website                 409376
rating                       0
rating_top                   0
playtime                     0
achievements_count           0
ratings_count                0
suggestions_count            0
game_series_count            0
reviews_count                0
platforms                 3986
developers                8366
genres                  103185
publishers              333401
esrb_rating             418553
added_status_yet             0
added_status_owned           0
added_status_beaten          0
added_status_toplay          0
added_status_dropped         0
added_status_playing         0
dtype: int64

In [3]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [4]:
df = df.drop_duplicates()

In [7]:
print(df.columns.tolist())

['id', 'slug', 'name', 'metacritic', 'released', 'tba', 'updated', 'website', 'rating', 'rating_top', 'playtime', 'achievements_count', 'ratings_count', 'suggestions_count', 'game_series_count', 'reviews_count', 'platforms', 'developers', 'genres', 'publishers', 'esrb_rating', 'added_status_yet', 'added_status_owned', 'added_status_beaten', 'added_status_toplay', 'added_status_dropped', 'added_status_playing']

In [ ]:
# For text columns
df.fillna("Unknown", inplace=True)

# OR fill different columns differently
df["genre"].fillna("Unknown", inplace=True)      # text
df["price"].fillna(0, inplace=True)               # number
df["rating"].fillna(df["rating"].mean(), inplace=True)  # average

In [8]:
# Check missing values first
df.isnull().sum()

id                      0
slug                    0
name                    0
metacritic              0
released                0
tba                     0
updated                 0
website                 0
rating                  0
rating_top              0
playtime                0
achievements_count      0
ratings_count           0
suggestions_count       0
game_series_count       0
reviews_count           0
platforms               0
developers              0
genres                  0
publishers              0
esrb_rating             0
added_status_yet        0
added_status_owned      0
added_status_beaten     0
added_status_toplay     0
added_status_dropped    0
added_status_playing    0
dtype: int64

In [12]:
# Fill missing values for your specific columns
df["metacritic"].fillna(0, inplace=True)                        # 0 = no score
df["website"].fillna("No website", inplace=True)               # unknown website
df["platforms"].fillna("Unknown", inplace=True)                # unknown platform
df["esrb_rating"].fillna("Not Rated", inplace=True)            # standard ESRB term
df["publishers"].fillna("Independent", inplace=True)           # common for no publisher

85                                   Kalypso Media||Kalypso
207                                           Vertigo Games
359       Square Enix||Feral Interactive||Warner Bros. I...
510                          Square Enix||Eidos Interactive
522                                             Square Enix
                                ...
473365                                         Sumo Digital
473569                                     Brightrock Games
474039        THQ Nordic||Nordic Games||www.handy-games.com
474060    Koch Media||Starbreeze Studios||Behaviour Inte...
474134                                         Kaia Studios
Name: publishers, Length: 1820, dtype: str

In [10]:
# Should show 0 for all 5 columns now
df[["metacritic", "website", "platforms", "esrb_rating", "publishers"]].isnull().sum()

metacritic     0
website        0
platforms      0
esrb_rating    0
publishers     0
dtype: int64

In [11]:
df.to_csv("game_info_clean.csv", index=False)
print("Done! File saved.")

Done! File saved.

In [13]:
df.drop(columns=["metacritic"], inplace=True)

In [14]:
print(df.columns.tolist())

['id', 'slug', 'name', 'released', 'tba', 'updated', 'website', 'rating', 'rating_top', 'playtime', 'achievements_count', 'ratings_count', 'suggestions_count', 'game_series_count', 'reviews_count', 'platforms', 'developers', 'genres', 'publishers', 'esrb_rating', 'added_status_yet', 'added_status_owned', 'added_status_beaten', 'added_status_toplay', 'added_status_dropped', 'added_status_playing']

In [15]:
df.to_csv("game_info_clean.csv", index=False)
print("Done! File saved.")

Done! File saved.

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 1820 entries, 85 to 474134
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1820 non-null   int64
 1   slug                  1820 non-null   str
 2   name                  1820 non-null   str
 3   released              1820 non-null   str
 4   tba                   1820 non-null   bool
 5   updated               1820 non-null   str
 6   website               1820 non-null   str
 7   rating                1820 non-null   float64
 8   rating_top            1820 non-null   int64
 9   playtime              1820 non-null   int64
 10  achievements_count    1820 non-null   int64
 11  ratings_count         1820 non-null   int64
 12  suggestions_count     1820 non-null   int64
 13  game_series_count     1820 non-null   int64
 14  reviews_count         1820 non-null   int64
 15  platforms             1820 non-null   str
 16  developers            1820 non-null   str
 17  genres                1820 non-null   str
 18  publishers            1820 non-null   str
 19  esrb_rating           1820 non-null   str
 20  added_status_yet      1820 non-null   int64
 21  added_status_owned    1820 non-null   int64
 22  added_status_beaten   1820 non-null   int64
 23  added_status_toplay   1820 non-null   int64
 24  added_status_dropped  1820 non-null   int64
 25  added_status_playing  1820 non-null   int64
dtypes: bool(1), float64(1), int64(14), str(10)
memory usage: 371.5 KB

In [17]:
df.describe()

,id,rating,rating_top,playtime,achievements_count,ratings_count,suggestions_count,game_series_count,reviews_count,added_status_yet,added_status_owned,added_status_beaten,added_status_toplay,added_status_dropped,added_status_playing
count,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000,1820.000000
mean,59213.666484,3.214319,3.476923,4.846154,63.422527,233.121978,444.913187,2.258242,235.272527,59.934615,851.204945,163.283516,45.765385,64.380220,18.791209
std,114800.528205,1.235920,1.363554,10.174641,80.029736,431.874401,171.818717,4.991726,435.869318,87.027762,1190.788866,359.560462,117.233430,109.385738,50.576113
min,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4283.000000,3.000000,3.000000,1.000000,0.000000,17.000000,324.000000,0.000000,17.000000,6.000000,63.000000,7.000000,2.000000,6.000000,0.000000
50%,16791.500000,3.570000,4.000000,3.000000,43.000000,66.000000,455.000000,0.000000,67.000000,24.500000,371.500000,31.000000,10.000000,21.000000,3.000000
75%,40101.250000,4.000000,4.000000,5.000000,91.000000,239.250000,570.000000,2.000000,244.250000,77.000000,1172.500000,134.000000,39.250000,73.250000,14.000000
max,520359.000000,4.810000,5.000000,211.000000,1307.000000,4289.000000,1238.000000,28.000000,4334.000000,635.000000,8298.000000,3533.000000,2325.000000,1056.000000,644.000000

In [18]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1820
Columns: 26